### ISSUE TITLE
Multiple plots at the same time

### ISSUE THREAD

**Issue by Sjesc** [r-wasm/webr#154]
I have been playing with this lib and react, and wanted to display 2 plots at the same time as this:

```jsx
<Plot webR={webR} script="plot(data)" />
<Plot webR={webR} script="plot(data2)" />
```

I managed to do it with a queue that sends the plot prompt and reads until no more `canvasExec` type messages are received, and I'm wondering if there's an easier way. 

Something that would help is a way to identify what prompt is generating the messages received with `webR.read()`, but I'm not sure if that's actually possible

**Comment by georgestagg** [comment]
From what I can tell of what you require, I think at the moment there are a couple of options for you,

1) If you are using [`webR.evalR()`](https://docs.r-wasm.org/webr/latest/api/js/classes/WebR.WebR.html#evalr) or similar to evaluate R code, you should be able to `await` the result to wait until the evaluation is complete. Then you can use [`webR.flush()`](https://docs.r-wasm.org/webr/latest/api/js/classes/WebR.WebR.html#flush) to get all the `canvasExec` type messages waiting in the queue for that plot.

2) Alternatively, if you are using [`webR.writeConsole()`](https://docs.r-wasm.org/webr/latest/api/js/classes/WebR.WebR.html#writeconsole) to send code to the R REPL, R will issue a message of type `prompt` when it has completed. You may be able to submit your plotting code, then read messages in a loop and collecting `canvasExec` output until a `prompt` message has been issued, indicating that evaluation is complete.

However, the downside of the above is that you must wait for one plot to finish before moving onto the next.

I can see that in the future we will probably want to handle this kind of situation more gracefully. Your suggestion is similar to how [Jupyter messaging keeps track of things, with a `parent` header on messages](https://jupyter-client.readthedocs.io/en/stable/messaging.html).

My gut feeling at the moment is that we will probably want to handle this by expanding [`Shelter.captureR()`](https://docs.r-wasm.org/webr/latest/api/js/classes/WebR.WebR.html#writeconsole) so that plots are captured in the same way that conditions and warnings are currently captured, with the plot (or plotting commands in the case of the `canvas` graphics device) returned as part of the captured output.

**Comment by Sjesc** [comment]
Hey, thanks for the response. I have been using the second approach. I was under the impression that it could be possible to not get all the messages needed to render the plot using flush after writing, it may make my code simpler. About the downside, yeah, I have to render one by one.

The `captureR` option could work as well, I'm gonna try to learn more about the project, maybe in the future I could help with this feature or others.

**Comment by WillemSleegers** [comment]
Would love to see some examples in the documentation on how to do this!

**Comment by jpjais** [comment]
Using for example the following R code : demo(graphics,ask=F, echo=F)
With canvasExec messages, i checked "clearRect" keyword to determine the start of a new plot and create a new canvas in the DOM.
With canvasImage  messages, how can we determine the start of a new plot ?

**Comment by georgestagg** [comment]
> With canvasExec messages, i checked "clearRect" keyword to determine the start of a new plot and create a new canvas in the DOM.

Ah, it was probably lucky that this was able to work previously. If the `canvas` device had been updated in the future to use the `clearRect` method somewhere else, this method would have broken.

At the moment, when the `canvas` graphics device invokes `newPage`, the current plot is cleared by running `clearRect` on the canvas context but no further signal is sent back to the main thread to indicate that this has happened. So, right now I don't think we can conclusively determine the start of a new plot.

However, I can see how such a signal could be extremely useful. Luckily, we have not released a version of webR containing the new `canvas` implementation yet, so we are free to tweak the message structure. I will expand the `canvas` messaging scheme to signal different events, including a `newPage` event message.

I'll be sure to add a plotting section explaining all of this to the documentation before the next release.

**Comment by jpjais** [comment]
thanks!

**Comment by bugzpodder** [comment]
@Sjesc is the implementation of Plot available anywhere? I'd love to use this in my react app as well!

**Comment by georgestagg** [comment]
Update: As of #243 the documentation now includes plotting information and an example of handling multiple plots with the Canvas graphics device.

https://docs.r-wasm.org/webr/latest/plotting.html

**Comment by bugzpodder** [comment]
@georgestagg awesome.  I tested it out that it works great for the demo shown in the docs.
Two things, one is that it was only available in latest/main (whats the difference?).  I had to import from https://webr.r-wasm.org/latest/webr.mjs to get the version I wanted but if I do keep this it will eventually break if additional API changes occur.  Just curious when 0.12 would be released?

Secondly, I noticed that `webR.flush()` used in the demo didn't seem to work with ggplot2 (no messages were flushed), however it did work in the REPL: https://webr.r-wasm.org/latest/ I am still doing some testing to see if it can be fixed.

Also, it isn't very clear to me when `dev.off()` and `webr::canvas()` is required or not.  it seem to work fine in the REPL without it.

```
webr::canvas() # optional
webr::install("ggplot2")
library(ggplot2)

# The mtcars dataset is natively available
# head(mtcars)
 
# A really basic boxplot.
ggplot(mtcars, aes(x=as.factor(cyl), y=mpg)) + 
    geom_boxplot(fill="slateblue", alpha=0.2) + 
    xlab("cyl")

dev.off() # optional
```

**Comment by georgestagg** [comment]
> one is that it was only available in latest/main (whats the difference?)

`/main/` and `/latest/` are aliases, they both point to the latest commit on the `main` branch.

> it will eventually break if additional API changes occur. Just curious when 0.1.2 would be released?

It is a possibility, yes. Version 0.2.0 will be released soon (within weeks), there is a release candidate at `/v0.2.0-rc.0/` that I'm currently using for testing. The final 0.2.0 release will be at `/0.2.0/`.

> I noticed that webR.flush() used in the demo didn't seem to work with ggplot2

I think this is probably to do with R's autoprint feature and how ggplot objects are evaluated. The REPL app has autoprint enabled in the console, but it is disabled by default with `WebR.evalR()`, etc. I think your suggestion of using `plot(gg...)` should work fine.

> it says it always defaults to `webr::canvas()` but you also have to run await `webR.evalRVoid('options(device=webr::canvas)');`?

The docs say "R’s default graphics device **can** be set so that `webr::canvas()` is always used for new plots." [emphasis added]. It means to say by running the provided command the default graphics device is set to be that way. I can see this is not ideally worded, I'll edit the docs making things a little clearer there before v0.2.0 release.
