### ISSUE TITLE
How to load only base package to speed up init()

### ISSUE THREAD

**Issue by jeroen** [r-wasm/webr#201]
Is it possible to only load the `base` package in `webR.init()`, similar to this in the console:

```sh
R_DEFAULT_PACKAGES=NULL R -e 'search()'
```

Related, is there a way to access `WebROptions` when importing with `require()` ? I am using this:

```js
const webr = require("@r-wasm/webr");
await webr.init()
```

But it's not clear to me how to access the WebROptions interface (I am using webr 0.1.1 from npm)

**Comment by georgestagg** [comment]
The `WebROptions` interface is a TypeScript feature designed to help with type checking, rather than a JavaScript object in the traditional sense.

Assuming that you are writing code directly in JavaScript, you can just create a standard JavaScript object to use for the webR `options` argument, and the [documentation for the TypeScript `WebROptions` interface](https://docs.r-wasm.org/webr/latest/api/js/interfaces/WebR.WebROptions.html) provides a guide for what shape that object should be.

One of the properties of the `options` object is `REnv`, a dictionary of environment variables to be used for the R process. With this, we can set `R_DEFAULT_PACKAGES=NULL` in the usual way.

---

The `require()` function should return an object containing the `WebR` class, which can then be used to instantiate a new `webR` instance. The constructor takes in the above-described `options` object as its argument.

So, I think you'll want something like this.

``` javascript
const { WebR } = require('@r-wasm/webr');
const options = {
  REnv: {
    R_HOME: '/usr/lib/R',
    R_DEFAULT_PACKAGES: 'NULL',
  },
};
const webR = new WebR(options);

await webR.init();
```

You might also need to wrap the final `await webR.init()` line in something like `(async () => { [...] })()`, if your JavaScript environment does not allow for top-level await.

---

Finally, it would be better if the user didn't have to set `R_HOME` in the options object above. The `options` object provided by the user should be merging with the defaults, but it looks like there's a bug there and it's not happening - I'll look into it.

**Comment by jeroen** [comment]
OK thanks! I am doing this in a nodejs so I think there is no downloading of the filesystem involved, or am I wrong?
Either way it didn't help much indeed 😄

**Comment by georgestagg** [comment]
The default env also sets `R_ENABLE_JIT: '0'`, but you're not picking it up due to #202.

I recall in my own testing R bytecode was slower in Wasm, but it was a long time ago when I tested it myself. Does adding the option back in with,
```
const options = {
  REnv: {
    R_HOME: '/usr/lib/R',
    R_DEFAULT_PACKAGES: 'NULL',
    R_ENABLE_JIT: '0',
  },
};
```
help at all?

**Comment by jeroen** [comment]
Ahh yes, now the results make sense. Adding `R_DEFAULT_PACKAGES` takes off 0.3 seconds in my test:

```js
const webr = require("@r-wasm/webr");
const webr_options = {
  REnv: {
    R_HOME: '/usr/lib/R',
    R_DEFAULT_PACKAGES: 'NULL',
    R_ENABLE_JIT: '0'
  },
};

function benchmark1(){
  var start = new Date();
  var session = new webr.WebR();
  session.init().then(function(){
    var end = new Date();
    console.log('Total time without options: ' + (end - start));
  })
}

function benchmark2(){
  var start = new Date();
  var session = new webr.WebR(webr_options);
  session.init().then(function(){
    var end = new Date();
    console.log('Total time with options: ' + (end - start));
  })
}

benchmark1()
benchmark2()
```

**Comment by jeroen** [comment]
I'll show you what I'm working on to give some context:

I added a feature to export datasets from R packages in r-universe. For example if you go to: https://tidyverse.r-universe.dev/ggplot2 then you can click a download link behind the dataset names:

---

![Screen Shot 2023-04-26 at 12 29 14 PM](https://user-images.githubusercontent.com/216319/234549470-d2b6dafb-7880-4b09-b33a-dba55b21338e.png)

---

This again opens a panel with in the bottom, the download links for the dataset as csv/rda.

These links then on the server load webr, extract the dataset from the package, and convert that to csv, which is done here: https://github.com/r-universe-org/cranlike-server/blob/master/routes/webr.js#L21-L65

It works, but the entire process is still quite slow.

**Comment by georgestagg** [comment]
That's neat! A shame that it is slow.

Since you are running webR server-side in any case, I wonder if it would be better to try and orchestrate things so that there are just one (or perhaps a fixed pool of) long-term webR sessions running instead. You could manage the memory use over time by cleaning up files on the virtual filesystem and using [`evalRVoid` or the `Shelter` mechanism](https://docs.r-wasm.org/webr/latest/objects.html) to evaluate R code.

This would avoid the high startup cost for each request and also means you could load packages like `writexl` just once at server startup. However, I understand that this might be tricky to organise if there are multiple requests for data coming in quick succession -- you certainly wouldn't want such requests to interfere with one another.

**Comment by georgestagg** [comment]
> Also maybe we can find a way to further reduce the init time with --vanilla or non-interactive?

You can do both with,
``` javascript
const webr_options = {
  RArgs: [ '--vanilla'],
  REnv: {
    R_HOME: '/usr/lib/R',
    R_DEFAULT_PACKAGES: 'NULL',
    R_ENABLE_JIT: '0'
  },
  interactive: false,
};
```
but I don't think it saves much further time. I have a hunch that most of the rest of the time now is spent spinning up a JS worker thread, decompressing and populating the virtual FS, compiling Wasm modules, and setting up other parts of Emscripten's infrastructure.

---

> I am worried about R using increasingly amount of memory if we keep loading more datasets and exporting them to the virtual filesystem.

Yes, things would need to be carefully kept separate and cleaned up. I think I would execute each request in its own environment, then instruct webR to [destroy](https://docs.r-wasm.org/webr/latest/objects.html#shelter) the environment when done, permitting R's built-in GC to clean it up later. Something like,

``` javascript
const envObj = await new webR.REnvironment();
try {
  await webR.evalRVoid('[... R code ...]', { env: envObj });
} finally {
  webR.destroy(envObj);
}
```
Of course, you'd still need to manage the files on the disk in some way.

---

Speaking of files, you might be able to save a little time by not writing the output to the virtual filesystem, but instead a raw atomic vector using `rawConnection`. Then you could return the data directly to JavaScript as a typed array,

``` javascript
const shelter = await new webR.Shelter();
try {
    const envObj = await new shelter.REnvironment();
    const result = await shelter.evalR(`
        df <- data.frame(x=c(1,2), y=c(-1,1))
        con <- rawConnection(raw(0), open = "r+")
        on.exit(close(con))
        write.csv(df, con)
        rawConnectionValue(con)
    `, { env: envObj });
    const out = await result.toTypedArray();
    console.log(out);
} finally {
    shelter.purge();
}
```
```
> Uint8Array(28) [34, 34, 44, ..., length: 28, Symbol(Symbol.toStringTag): 'Uint8Array']
```

And perhaps there's a similar way to pass raw atomic vectors in through the `new REnvironment()` to avoid having to copy the lazyload database files to disk, though that seems harder to me at first glance.
