### ISSUE TITLE
Any plan for synchronous results?

### ISSUE THREAD

**Issue by WebReflection** [r-wasm/webr#234]
We're going to release *py-script* *next* *TP* (Technical Preview) and we have homogeneous helpers for *pyodide*, *micropython*, *wasmoon* and *ruby* but while [trying to add R](https://github.com/pyscript/pyscript/pull/1559) we found a few discrepancies with other WASM (EMScripten) based interpreters/runtimes, most notably the fact that it's apparently not possible to execute *R* synchronously, even if we have orchestrated *synchronous* *non-blocking* *DOM* and *globalThis* main context access via Web Workers.

We need to adjust a bit of logic to welcome *WebR* but as we also write documentation around enabled interpreters, it'd be awesome if we could have a way to provide also a *synchronous* `run` whenever that's meant/needed, thank you.

**Comment by georgestagg** [comment]
Hi, it's exciting to see the prospect of webR included as part of py-script!

Unlike the other Wasm-based interpreters you mention, we decided very early in development that webR should launch and manage its own web worker to run the R Wasm binary and execute code in the worker thread. The benefit of this is that we can ensure that all users making use of webR are able to perform long-running R computations without locking up the browser tab.

The downside of this approach is that the communication between the main thread and worker thread is inherently asynchronous, based on message passing with `postMessage()`. In webR, we use some `SharedArrayBuffer` and/or service workers techniques to block the worker thread when required (primarily, blocking to wait for input from the user). Unfortunately, as far as I know the same techniques are not able to block on the main thread. Some tricks like sync XHR on the main thread might work, but I know that technique is deprecated.

I think running R code directly on the main thread would allow us to run code synchronously, but that would require a restructuring of our entire supporting architecture to avoid the async message passing. Since we also cannot easily block the main thread to wait for a response from the worker thread, we currently have no plans to introduce a synchronous version of the `evalR` command.

I'm going to close this as "not planned" for now, but I do welcome further comments in the discussion. We might be able to revisit things in the future as the browser environment evolves and webR becomes more mature.

**Comment by WebReflection** [comment]
> The benefit of this is that we can ensure that all users making use of webR are able to perform long-running R computations without locking up the browser tab

That's what we do too in py-script, the *XWorker* is fully based on Atomics and SharedArrayBuffer and executes sync-like code in a worker without ever blocking the main thread.

*Enter events* ... it's impossible to call `stopPropagation()` or a `preventDefault()` asynchronously and it's extremely hard to forward to the Worker the currently running event at the time it's valid, and running ... yet we can do that too.

That being said, we [coincident](https://github.com/WebReflection/coincident#readme) we enable a world of possibilities behind the scene but webR in there would inevitably **double** every single interaction because it would create its own *async* orchestration *even* if spawn in a Worker ... imagine I can use MicroPython (or JS, or Lua) on the UI (light, fast) for non blocking operations but delegate to webR operations in the Worker ... if we could have a way to disable the async nature of webR there would be way less moving parts still preserving the non blocking nature of this project (as it would already run in a worker, like we do with Pyodide for more complex Python things).

If this project won't ever consider offering a sync ability to evaluate code, we'll need to consider carefully if it should be part of the list of PLs we'd love to offer because the amount of things that can't possibly work out of the box, compared to other PLs, might be overwhelming for our users.

Thanks for considering (at least) the possibility to simplify all your stack and just execute right away when that's desirable and, still, non-blocking.

**Comment by georgestagg** [comment]
Just a quick note to add that in the current development version of webR we use Emscripten features that absolutely depend on the R Wasm binary running in a Web Worker. For example, we make use of dynamic libraries (`libRlapack.so`, `libRblas.so`, R package libraries) that are downloaded on demand with a sync XHR, along with Emscripten's [FS.createLazyFile()](https://emscripten.org/docs/api_reference/Filesystem-API.html#FS.createLazyFile) so that virtual filesystem content is not downloaded unless it is requested.

So, I think we are always going to need to orchestrate our own web worker and indirection/proxy scheme on behalf of webR users, at least for the standard public API. I don't think it is reasonable for us to simplify too much, as this just passes on the responsibility of web worker setup and communication onto our users, who would then need to learn how to use coincident, comlink, or otherwise organise their own communication of R object data to and from the web worker.

I wonder if rather than trying to add a synchronous evaluation function to our API on the main thread, a better way forward might be for us to expose some of our current webR worker thread infrastructure as a new module available separately for advanced users to import. In situations such as this one, where there is already a pre-existing Worker infrastructure and communication system in place, I think this would allow those advanced users to skip the worker setup and just integrate a selection of webR functions into their own worker scripts.

This would involve formalising and making public several of our internal webR functions and communication channel interfaces that exist on the worker thread, but I think it should be possible. I imagine that the [captureR()](https://github.com/r-wasm/webr/blob/main/src/webR/webr-worker.ts#L531) function, in particular, is a prime candidate to make public and integrate with py-script, as this function executes code synchronously on the worker thread and captures the output in preparation for transmission back to the main thread.

I will think some more about this after our currently planned v0.2.0 release and get back to you with any further thoughts.

**Comment by WebReflection** [comment]
> as this just passes on the responsibility of web worker setup and communication onto our users, who would then need to learn how to use coincident, comlink, or otherwise organise their own communication of R object data to and from the web worker.

these are all implementation details for us ... literally nobody needs to know anything about *coincident* (or comlink) in our Technical Preview, it's all seamlessly integrated ... you just write your PL of choice code and it just works, we take care of the rest.

> I think this would allow those advanced users to skip the worker setup and just integrate a selection of webR functions into their own worker scripts.

This would be absolutely form our side ... and ... 

> I imagine that the [captureR()](https://github.com/r-wasm/webr/blob/main/src/webR/webr-worker.ts#L531) function, in particular, is a prime candidate to make public and integrate with py-script

I've already tried that without success because it was still async ... we do bootstrap (inevitably) interpreters/runtimes asynchronously but if everything is still async after we have issues explaining nothing works out of the box like other PLs do and that would end up to end users as thing to digest/think about ... while ideally we'd love to have R non blocking for complex stuff (like you do already) out of a worker which is already non-blocking and it's orchestrated to operate seamlessly with the main thread DOM/UI/namespace in general ... but writing something like `await` in a worker, per each *R* step, won't go too far in terms of DX *and* UX, imho.

**Big Thanks** for considering advanced usage and hopefully enabling *PyScript* to provide this project without much explanation needed around its logic (compared to other interpreters already available)!

**Comment by WebReflection** [comment]
P.S. the lazy FS should not be a problem neither ... we just need to add documentation around EMScripten FS that could be sync or not, but that would be it.
