### ISSUE TITLE
Reflexion about how to package a webr app

### ISSUE THREAD

**Issue by JeremyPasco** [r-wasm/webr#246]
Hi,
Thanks for the amazing work done here. Do you have any thought on how to reduce boot time for webr app?
To be more specific: let say a team has developed a webr app which requires many libraries. For now each user will have to wait for:
- R WASM to be downloaded
- then each library to be downloaded + installed

This can easily lead to >1min boot time. In some contexts it is a huge barrier.

I was wondering if it would be possible to:
- download R wasm+specific packages in parallel? (not waiting for R wasm to be downloaded to start downloading packages)
- or load some "snapshot" session in which all packages would already be installed?
- some sort of tree shaking to reduce final app size as Webpack does but for R code? (not even sure if it's possible with R packages)

**Comment by georgestagg** [comment]
Hi,

A minutes long boot time sounds quite long, even when including many packages. Do you find the same slow load times when downloading packages on the demo app at https://webr.r-wasm.org/v0.1.1/? Does refreshing the page and installing the packages again then happen quicker?

In theory, once packages are downloaded once on your machine, they should be cached by your browser and load quickly from that point on. However, you are possibly hitting a particular issue I know of that has been fixed in the latest build of webR, but has not yet been released to npm. If possible, and you are willing, you could perhaps try switching to the v0.2.0 release candidate at [webr@v0.2.0-rc.0](https://www.npmjs.com/package/webr/v/0.2.0-rc.0), due to be released soon. That version does not have that particular bug I am thinking of.

Also, please ensure if possible that you are [serving your app with Cross-Origin Isolation headers](https://docs.r-wasm.org/webr/latest/serving.html) set. It involves configuring your web server, or hosting service such as Netlify, to serve your content with the HTTP headers,

```
Cross-Origin-Opener-Policy: same-origin
Cross-Origin-Embedder-Policy: require-corp
```

For version 0.1.1 of webR it makes an **extreme** improvement to the performance of your app and the only place I am aware of so far where this is not really possible is in GitHub pages.

---

For version 0.2.0 of webR we have made several improvements to reduce the download size of the core webR application, making use of a "lazy" filesystem mechanism provided by Emscripten. We also hope to bring similar changes to packages in the future, though it has not yet been implemented yet. It is similar in scope to tree-shaking, files that are not immediately required to load R are instead downloaded only when they are requested. With the lazy filesystem mechanism, a download of the core R system in version 0.2.0 of webR will be around 25% of the download size for v0.1.1.

**Comment by georgestagg** [comment]
With the release of v0.2.0+ of webR this should hopefully be improved, with even further performance improvements merged for the next version of webR.

Since this is essentially the same issue as #300, I'm going to close this one in the interest of keeping our issues organised. If you're still having problems with R package downloading and long load times, feel free to comment with examples and your experience there.

> [Is it possible to...] load some "snapshot" session in which all packages would already be installed?

I'm currently working on an R package that will allow users to build filesystem images of R package libraries that can be loaded into webR in this way. Keep an eye out for that in the coming weeks. Once released, any issues with that process can be opened on that project's own GH repo.
