### ISSUE TITLE
Printing R help files in the console

### ISSUE THREAD

**Issue by michaelt918** [r-wasm/webr#257]
When using `help()` or `?` in a webr code cell, you get an error. For example, I entered 

`help(mean)`

in the code cell on the [documentation index page](https://docs.r-wasm.org/webr/latest/) and the output was

`Warning in file.show(temp, title = gettextf("R Help on %s", sQuote(topic)),  :
  system call failed: Function not implemented
Warning: error in running command`

There is an [R-bloggers post](https://www.r-bloggers.com/2013/06/printing-r-help-files-in-the-console-or-in-knitr-documents/) providing a method that fixes this problem by printing the help file to the console. Could this be added to webR by default?

**Comment by georgestagg** [comment]
The issue here is that R wants to run an external pager program to show its help files, and the `system()` command is not able to run under WebAssembly. In fact, even if it could, there's no external pager program installed on the virtual filesystem.

So, webR requires an alternative way to handle pager requests. There's a helper function [webr::pager_install()](https://docs.r-wasm.org/webr/latest/api/r.html#generate-an-output-message-when-file-is-displayed-with-the-pager) provided by webR that installs a pager that then outputs webR messages of `type: 'pager"`, but this is only really useful for developers that are creating applications containing webR as a component.

For example, the webR REPL app at https://webr.r-wasm.org/latest/ uses this feature to link up the Code Editor component to the pager mechanism. So, running help commands in that app should work OK. Probably the webR documentation pages should be updated to also handle this gracefully.

With a little extra setup, it's possible to install your own pager. The code,

``` r
options(pager = function(files, ...) { writeLines(readLines(files)) })
?help
```

might work, for example. However, in truth it's up to the application loading webR into the page in how it should handle pager requests (and therefore how documentation appears), so I don't want to enforce any particular default here.

**Comment by coatless** [comment]
Great to see this discussion is already formed! Just received a question on this the other day. 

So, to implement the helper file improvements, the main changes being recommended are:

1. after the WebR initialization to trigger `webr::pager_install()` inside of a `await webR.evalRVoid()`; and, then, 
2. filter the evaluation output of code to determine if it's `type: 'pager'`.

From the `repl` app, this would look a bit like: 

https://github.com/r-wasm/webr/blob/cca45bced9d0afa0b72b21197c83faa605bd63ca/src/repl/App.tsx#L91-L96

https://github.com/r-wasm/webr/blob/cca45bced9d0afa0b72b21197c83faa605bd63ca/src/repl/App.tsx#L114-L118

<details>
<summary> Source of `webr::pager_install()` </summary>

https://github.com/r-wasm/webr/blob/cca45bced9d0afa0b72b21197c83faa605bd63ca/packages/webr/R/pager.R#L12-L29
</details>

**Comment by georgestagg** [comment]
Yes, that's currently the best way to deal with help documentation, since it uses R's pager system by default.

After running `webr::pager_install()`, help documentation will instead trigger a webR message (with a `type` property of `'pager'`) on the output communication channel. The messages are obtained using e.g. `webR.flush()`.

This is similar to how the output of images from the canvas graphics device works, and so will probably need to be handled [in the same place](https://github.com/coatless/quarto-webr/blob/main/_extensions/webr/webr-context-output.html#L42).

The messages contain a `path` and `title` properties, and the documentation content will exist on the virtual filesystem at the `path` given. So, you'll need to use [`webR.FS.readFile()`](https://github.com/r-wasm/webr/blob/cca45bced9d0afa0b72b21197c83faa605bd63ca/src/repl/components/Editor.tsx#L253) to read the contents of the file and then display it in some way on the page.

Note that due to how the system works in R, it is sometimes your responsibility to clean up after reading the file and displaying the content, that is why there's a `webR.FS.unlink(path);` in the snippet above.

**Comment by coatless** [comment]
@georgestagg thank you for the insight! The `pager` event type is now available. The help documentation looks great now! 

<img width="1212" alt="Demo of the pager event working" src="https://github.com/r-wasm/webr/assets/833642/1cb8abbc-9826-4e6d-a58c-4f68897ac7e2">

**Comment by georgestagg** [comment]
Great! Since this seems to be working well in practice I'll close this issue.
