### ISSUE TITLE
Fully Worked Example should link to the "Serving Pages with WebR" page

### ISSUE THREAD

**Issue by JosiahParry** [r-wasm/webr#266]
Going through the docs and I'm trying to use the fully worked examples. 

The first example [Creating an interactive webR REPL console](https://docs.r-wasm.org/webr/latest/examples.html#creating-an-interactive-webr-repl-console) cannot be reproduced. I understand that webR should be loaded via cdn but nonetheless I've double checked that I have webR installed via npm.

**Comment by georgestagg** [comment]
Yes, webR should be loaded from `https://webr.r-wasm.org/latest/webr.mjs` in this example, no npm needed.

Sometimes, this URL is caught up with caching issues as I commit changes to `main` and they are pushed to AWS, but versioned URLs such as 'https://webr.r-wasm.org/v0.2.0/webr.mjs' should always work.

The example currently works for me. Can you let me know more information about what goes wrong at your end, exactly? Does the page load at all? Are there any errors or messages in the JavaScript console? Does it work in other browsers? Any information at all is useful here, so we can improve the documentation for future readers.

**Comment by JosiahParry** [comment]
Thanks @georgestagg! I'm not a JS dev so I apologize for my lack of repro abilities! This shows up in the browser inspect tools (Chrome) when using `/latest` or `v0.2.0` as the URL.  
<img width="411" alt="image" src="https://github.com/r-wasm/webr/assets/13534508/0d4514c5-aa9c-4942-a72d-b2136b8d20bd">

I can use the run box but it just outputs what I put into it. 
<img width="323" alt="image" src="https://github.com/r-wasm/webr/assets/13534508/6412489b-a50b-4b17-8dfb-347019446882">

**Comment by JosiahParry** [comment]
I've downloaded `webr-serviceworker.js` and `webr-worker.js` and included them in the root of my "app" and the console now loads. I suspect there may be pathing issues in one of those files?

**Comment by georgestagg** [comment]
> I'm not a JS dev so I apologize for my lack of repro abilities!

No worries, I expect there'll be lots of R users interested in webR, but without JS experience. If you're just interested in a runnable R editor in a page, and you're already using Quarto, the [quarto-webr](https://github.com/coatless/quarto-webr) extension makes everything easier for non-JS devs.

---

> I've downloaded `webr-serviceworker.js` and `webr-worker.js` and included them in the root of my "app" and the console now loads.

Ah ha! Yes, this happens when webR is not being served with the required HTTP headers. There's a couple of possible fixes:

 * Tweak your server setup to serve your app with the required COOP/COEP headers
 * Create `webr-serviceworker.js` and `webr-worker.js` in the root of your app

It sounds like the second method is working for you, but note that the performance will be significantly impacted. The first method is better, if possible in your setup. Also note that you don't need the full content of those files, you can forward the request onto the CDN with
```
importScripts('https://webr.r-wasm.org/latest/webr-serviceworker.js');
```
in the file `webr-serviceworker.js`, for example.

The documentation has more information about all of this at https://docs.r-wasm.org/webr/latest/serving.html

**Comment by JosiahParry** [comment]
Important info! Thank you. Perhaps a `:::{.callout-note}` under the fully worked example could be added with that clarification? It could save other folks like myself some headaches :)

**Comment by georgestagg** [comment]
Thanks again, in 4778dbd I've added a link to the "Serving Pages with WebR" page that explains all the details, just after the HTML Console example.
