### ISSUE TITLE
readr::read_csv("https://...") does not work read.csv works("https://...")

### ISSUE THREAD

**Issue by idot** [r-wasm/webr#314]
Hi, 
I hope its the correct project to report this.

Loading data with readr::read_csv never finishes
Loading data with read.csv works

[example on shinylive.io](https://shinylive.io/r/app/#code=NobwRAdghgtgpmAXGKAHVA6ASmANGAYwHsIAXOMpMAGwEsAjAJykYE8AKAZwAtaJWAlAB0IIgMQACACJwAZnzgSAqgEkJsoowlpUE0tyikJAE2YB3Ttom9OpIgHNmMCQFo3LkQFdaEgDwv1am9jAAUoezh2EREJCUkAQXQ9WlJqRXcPCFjSFLSwiDhqKLAACULqIgkAZV5+AEIhMAFcaKy46tpjOHoWCWooViJPIzMU7gk+VGHtCGMJIdIpoy75CBTaEksMmIlOTu6WABkBhajRNtjJKv2erVQoAup1TQmIJa33Hdi9rtv8wrOX1i7RUb2GiGqdC6Wg0Wn0iggnhg9DgWiIsgk9D4HzcQO+UNRoKW7EmwxUcwAvBJGliIJxGi0LsDmSzgf0UU8qY0AHJIlFojG0ziIBl41nimB8CRUgCMjPFCuBMCgAA9pRIAKwABnlioVADcoEFFFSAMxa4TnZnNVrMyQAWSgUvuj2eWmMtE4qH6rD49nmw3erk+TOVfH+RVtLMkAHlA+CJCVPXZHLBg7imbFvURSHHFsN2AsluT1Y0PbYQhVSI1LUDLbFLbWIJIZKtFJxUfrUX0HLQCBJGHAAI7eQdzOwmcxWGwppzpzIdxhdrT+dSeCAEHIkElg0i4AP50gCCQgKOSJO2Bxz9F6biKGPUOYAMSd+lknieAHE4KxF9JDFA847JIoz6AOw6eHAthwHMiLIt2N5CsBEgACo2BIcAqqgg6cHsJC3oYEgRAUzDkJYgEzleaaehIZjMOgMGvFYBBGtQyEToOsyopWOZ6JUfAeix5AEaQIptGIyEyhgEgqEYNGNIOUCbrQXaNDM453oOsLttwQyPpiihQMMRDKjkLHUNQrDIcCg4uJhcAEMMjFmHeWSkqQlg7ksAAkQrHgQBgQBEyEAEzSbJlhFtMpCsKgig0YB2bVm0UWkN55akDxRirpx0JZewp5WsCarAqusivtw77UN5Zivn6QJCn4AQdkO7CShA7Aqs0EjKiqnXdWkQX6BgCzqu5vnYhIADUEgyk2zIzp1+5MHAUAANaWFSQr7sQnLUmAYgAOwavE8RSAAQgymKaNCpZgC5KRwKKmbMiq7J3QA6nVQXJPAfESAUKpGKinioFuWQ7j12LCHgYpKk6WRcqUyZUc4N61esP05PA9JNFGsQAL5NgTrQwKQ-aro03CkIswoAPR0-YyYYEz+iePQniLsQZAUKQGDEDAdMdg8a2MEQuF01AAAsMohcYsj0MYAAcSv0Kaxj0IdWqa1L9B0+YdMarIIWmrIACcZumgQyuHQQIVK1bcCHQAbM7TtKc7ashWbcBOwQdtwDKxgynTZMsYwnD85w+qNCI2F8KQxSKcYUcx3jswyk14FQCnBDR215OWvHZBJ6tufRyYJBPenxeJ8HTa16XOcAPp52nlrGCFWfJ4wiCIMnrf52HReMAnTfGIP+qVwUNZx6PJed02kgAMKKcJNR8Kw2hJNsdK1KwiSoOw3jqt4+6Lsu6oX6ilpgATAC6QA) where "read_csv done" is never printed to console
There is a warning ```preload echo:`curl` package not installed, falling back to using `url()` ```

Otherwise awesome project!

```r
mtc <- "https://gist.githubusercontent.com/seankross/a412dfbd88b3db70b74b/raw/5f23f993cd87c283ce766e7ac6b329ee7cc2e1d1/mtcars.csv"
print("read.csv")
d1 <- read.csv(mtc)
print("read.csv done")
print(d1)

print("read_csv")
d2 <- readr::read_csv(mtc)
print("read_csv done")
print(d2)
```

**Comment by georgestagg** [comment]
Thanks for reporting this. It looks like the Wasm compiled `vroom` package gets stuck in a lock during `readr::read_csv()`.

Until we track down the bug further, you will need to stick to using the `read.csv()` function instead.

**Comment by stobor827** [comment]
I ran into (I assume) the same issue with readr::read_lines with an http or https url.
Interestingly, vroom( url )  with a random html page does not hang, it errors with an unknown delimiter error.
If I pass a delimiter, then it does hang.  So that might help narrow down the location/scope of the lock?

For others who find this issue, readr does have an option for opting into the pre-vroom implementation, which works for me.  (Obviously without the performance benefits of vroom...)
`with_edition(1, read_csv("my_file.csv"))`
https://www.tidyverse.org/blog/2021/07/readr-2-0-0/

I did try setting a few of the VROOM env vars to be sure it wasn't trying multiple thread or progress indicators, but this didn't change anything.
I'd be interested to work on finding a fix for this, but don't have much experience with js or wasm debugging.   If there are good resources for getting started in this, I could try my hand at it!

**Comment by georgestagg** [comment]
The following also sets up readr to use the pre-vroom implementation:

```r
options("readr.edition" = 1)
```

It would be good to get this up and running properly, particularly for Quarto Live tutorials. Will try to find some time for a deeper debugging session soon.

**Comment by georgestagg** [comment]
A fork [r-wasm/vroom@webr](https://github.com/r-wasm/vroom/tree/webr) has been created with some changes to make the package compatible with webR. The webR public package repository has been updated to use this version of the package, and so `readr::read_csv()` should no longer hang.
