### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by coatless** [r-wasm/webr#353]
I was recently asked if there was a citation for `{webR}`. I'm not sure if a technical report or an archive of the repository was placed on Zenodo. So, is there a preferred citation for `{webR}`?

If not, would the following be okay to recommend? 

> Stagg, G and Henry, L. webR: The statistical language R compiled to WebAssembly via Emscripten, for use in web browsers and Node. 2023. https://github.com/r-wasm/webr/

**Comment by georgestagg** [comment]
There is currently no preferred citation or a published report for webR. At some point, we should use Zenodo (or otherwise publish) to get a DOI and update the repository with a `CITATION` file. I'll leave the issue open to remind myself to revisit that in the future.

In the meantime, something along those lines looks reasonable. I would suggest just a few minor changes:
 * Slightly shorter title,
 * Use `et al.` since there are now more contributors to the GitHub repository,
 * Cite a specific version,
 * Very minor: I tend to use my middle initial for citations.

So, something like:

> G. W. Stagg, L. Henry, et al. webR: The statistical language R compiled to WebAssembly via Emscripten, 2023, version 0.2.2. https://github.com/r-wasm/webr

Or, in bibTeX,

```BibTeX
@manual{webr,
	title        = {webR: The statistical language R compiled to WebAssembly via Emscripten},
	author       = {Stagg, G. W. and Henry, L. and others},
	year         = 2023,
	url          = {https://github.com/r-wasm/webr},
	note         = {Version 0.2.2}
}
```
