### ISSUE TITLE
Problem mounting glue image

### ISSUE THREAD

**Issue by tim-newans** [r-wasm/webr#361]
I've set up a code editor in Kajabi (course builder site) and the code window is working as expected with base R and installing packages. However, whenever a package requires `glue`, it comes up with the following error:

<img width="675" alt="image" src="https://github.com/r-wasm/webr/assets/69664059/f1bc6d4b-7d5e-4d96-98ae-4360a946a2e2">

Any advice on this?

**Comment by georgestagg** [comment]
Does this also happen for you on https://webr.r-wasm.org/latest/?

I am unable to reproduce the issue on my machine, so I cannot investigate further without more information. Do you see any errors in your browser's developer console? Do you have some way to provide me access to a page showing the problem so that I may investigate further directly?

**Comment by tim-newans** [comment]
Seems like this may have been a caching issue, have come back to it after the weekend, and all seems to be running fine. Thanks for all your work on webR, I'm loving it!

**Comment by bugzpodder** [comment]
a user is reporting this issue too
