### ISSUE TITLE
Prevent fetching R.bin.data & R.bin.wasm etc on each page load

### ISSUE THREAD

**Issue by JosiahParry** [r-wasm/webr#438]
I am working on Rust bindings to WebR https://github.com/JosiahParry/webr-js-rs. Since WebR cannot be built for WASI yet, this relies on loading webR from the `.minjs`. 

However, what I've noticed is that the minjs loads the following files on each page load: 

- R.bin.js
- R.bin.data
- R.bin.wasm
- libRlapack.so
- libRblas.so
- DESCRIPTION

These result in `6.6mb` of file downloads per page load:

```r
file_sizes <- c("177KB", "4.1MB", "1.7MB", "597KB", "48.8KB", "631B")
sum(fs::as_fs_bytes(file_sizes))
#> 6.6M
```

which is quite a lot! 

The ideal behavior I would like is to download these files just _once_ and then cache them and use them. 

However, I have pretty much no idea about how JavaScript bundling / packaging works. 

Is there a way to build webR to accomplish this type of behavior?

**Comment by JosiahParry** [comment]
Following the trail: 

- https://webr.r-wasm.org/latest/webr.mjs loads
- https://webr.r-wasm.org/main/webr-worker.js which then loads
- https://webr.r-wasm.org/main/R.bin.js which then does a whole lot of stuff at 
- https://webr.r-wasm.org/main/R.bin.js

**Comment by JosiahParry** [comment]
Looking into the headers of the requests the Cache-Control is not set. It would be great to be able to have the headers set so that subsequent requests can just use the cache. Or perhaps have a way to set the cache type upon load?

I think an issue that I may be running into is that webr loses its context on each page because it continually is reloading itself 

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control

**Comment by georgestagg** [comment]
The webR CDN assets under /latest/ are intentionally served with `Cache-Control: no-cache` so that the latest commit is always downloaded by the browser.

The longer-term builds under e.g. /v0.3.3/ are served with the HTTP header `cache-control: max-age=604800`, and so the webR assets should automatically be cached by browsers for 1 week.

Assets are also served compressed over the wire where the browser supports it (brotli, gzip), which should hopefully help.

This 6mb of download is already a pretty slim distribution of the R WebAssembly binary and the required filesystem data starting up R and its default packages. We attempt to segment the virtual filesystem so that only the minimal required binaries and filesystem data are downloaded on initial load. You may notice that as you use R, further filesystem data is downloaded on demand. For example, loading a help file, or plotting an image with e.g `png()`, will initiate further download of assets.

**Comment by JosiahParry** [comment]
Thank you! I'll give this a look!

**Comment by JosiahParry** [comment]
Thank you for this! I've been able to swap out the `/latest/` with `v0.3.3` and the caching is now present. Also noticed I had this bad boi checked! 
<img width="108" alt="image" src="https://github.com/r-wasm/webr/assets/13534508/f3cb9e2a-80e9-4c70-9017-375f61c1ca0e">

What I did notice is that even though these are cached, the R session will restart on a refresh. I will have to explore what this means for mounting data and installing packages.
