### ISSUE TITLE
Reticulate Package on WebR

### ISSUE THREAD

**Issue by vsk-1167** [r-wasm/webr#496]
Hi WebR Team, 

I am building a shiny app that depends on 'sklearn' functions that I've locally used 'Reticulate' to call. 

I am met with the error that "Reticulate" is not found in the 'webR binary repository' when following steps to build a serverless shiny app using 'ShinyLive'.

My questions are: 

1. Is "Reticulate" incompatible with webR architecture due to its Python dependency? 
2. If that isn't necessarily a limitation, are there steps to get this R package up on WebR? I can work on this if so. 

Please let me know if you have any suggestions, or thoughts on the questions above.

**Comment by georgestagg** [comment]
Hi,

I'm sorry, but reticulate is not currently available for webR and likely won't be for quite some time.

It's probable that reticulate would need a lot of work, or even a re-implementation, to work with a WebAssembly build of Python. In addition, right now webR is unable to spawn subprocesses. So, even if reticulate were available it would not be able to start a Python process to work in. Enabling subprocesses will be a fairly technical addition to webR, requiring work to spin up further JavaScript Web Workers and manage the communication between workers.

I'm going to close this issue as "not planned" for the moment, but we might revisit in the future once we have subprocesses working. Though, at that point we'll probably start by focusing on additional webR processes, rather than Python processes, to begin with.

In the meantime, I recommend that you migrate your Shiny app to Shiny for Python. This will allow you to keep your app entirely in the Python world, giving you access to sklearn in Wasm, through Pyodide and Shinylive for Python.
